language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

env:
    - LIBRE=re-0.4.17 LIBREM=rem-0.4.7

sudo: require

addons:
    apt:
        packages:
            libssl-dev

install:
    - curl "http://www.creytiv.com/pub/${LIBRE}.tar.gz" | tar xzf -
    - curl "http://www.creytiv.com/pub/${LIBREM}.tar.gz" | tar xzf -
    - curl -OL 'https://github.com/alfredh/pytools/raw/master/ccheck.py'
    - for p in ${LIBRE} ${LIBREM}; do cd $p && sudo PATH="$PATH" make install && cd - && sudo rm -Rf $p; done
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi

script: 
    - make V=1 CCACHE= info test
    - python2 ccheck.py
