name: Tools

on: [push, pull_request]

jobs:
  tools:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install pylint
      run: sudo apt-get update && sudo apt-get install -y pylint
    - name: pylint
      run: pylint tools/fritzbox2baresip
