name: Tools

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
      with:
        args: "pylint tools/fritzbox2baresip"
